env:
  browser: true
  es6: true
  jest: true
  node: true
extends:
  - eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  array-bracket-spacing:
    - error
    - never
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
  object-curly-spacing:
    - error
    - always
    - objectsInObjects: false
  quotes:
    - error
    - double
    - avoidEscape: true
      allowTemplateLiterals: true
  semi:
    - error
    - never
  sort-imports:
    - error
    - ignoreCase: true
