name: Publish
on:
  release:
    types: [created]
jobs:
  npm:
    name: NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm run build
      - run: |
          VERSION=$(echo ${{ github.ref_name }} | cut -c 2-)
          npm version $VERSION --no-git-tag-version
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
